version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          - v1-dependencies-

      - run: sbt test

      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2/cache
          key: v1-dependencies--{{ checksum "build.sbt" }}

      - store_test_results:
          path: ./target/junit

workflows:
  version: 2
  test:
    jobs:
      - test
