version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      CACHE_VERSION: v3

    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "project/plugins.sbt" }}-{{ checksum "build.sbt" }}
          - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "project/plugins.sbt" }}
          - dependencies-{{ .Environment.CACHE_VERSION }}

      - run: sbt coverage test coverageReport
      - run: bash <(curl -s https://codecov.io/bash) -Z
      - run: mkdir -p ./target/junit && cp -R ./target/test-reports ./target/junit/test-reports

      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2/cache
            - ~/.sbt
          key: dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "project/plugins.sbt" }}-{{ checksum "build.sbt" }}

      - store_test_results:
          path: ./target/junit
